### ISSUE TITLE
Windows 10 Support

### ISSUE THREAD

**Issue by ben3005** [protonet/cordova-plugin-image-resizer#10]
Would it be possible to add windows 10 support.

I don't mind creating a pull request to implement this feature myself.

**Comment by JoschkaSchulz** [comment]
if you are creating a pull request I can merge it... would be great also if some other ones can test it too

**Comment by JoschkaSchulz** [comment]
awesome pull request, thank you

https://github.com/protonet/cordova-plugin-image-resizer/pull/12
