### ISSUE TITLE
Webkit error in iOS

### ISSUE THREAD

**Issue by GomatoX** [protonet/cordova-plugin-image-resizer#16]
WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> **\* -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]

**This code cause silence in ios:**

```
PHFetchResult *savedAssets = [PHAsset fetchAssetsWithLocalIdentifiers:@[fileName] options:nil];
   [savedAssets enumerateObjectsUsingBlock:^(PHAsset *asset, NSUInteger idx, BOOL *stop) {
       //this gets called for every asset from its localIdentifier you saved

       [[PHImageManager defaultManager]
        requestImageDataForAsset:asset
        options:imageRequestOptions
        resultHandler:^(NSData *imageData, NSString *dataUTI,
                        UIImageOrientation orientation,
                        NSDictionary *info)
        {
            sourceImage  = [UIImage imageWithData:imageData];
        }];

}];
```

**Comment by okhioktanio** [comment]
After reading the ImageResizer.m code using Xcode, it seems you have to specify the file name on the options.

var options = {
                  uri: uri,
                      **_folderName: "Protonet Messenger", //mandatory for android_**
                      quality: 90,
                      width: 1280,
                      height: 1280,
                  **_fileName: 'resize.jpg' //mandatory for iOS_**
                  };

**Comment by Spracto** [comment]
I experienced the same bug. Specifying fileName resolved it.

**Comment by cataragak90** [comment]
hmm, at least I can see something.
I have a full white image instead of the resized one

**Comment by duca14036** [comment]
@cataragak90 try to replace this file https://github.com/duca14036/cordova-plugin-image-resizer/blob/master/src/ios/ImageResizer.m

**Comment by kaz-tk** [comment]
@duca14036 I tried your ImageResizer.m, but imageData is nil
so, callback function get no filePath.
imageRequestOptions.synchronous not working

**Comment by wstrinz** [comment]
Also getting an "all white" image, also tried @duca14036 's fix, and am also getting an `error save image` result.

**Comment by howawong** [comment]
Hi, any update on this issue?

**Comment by aligorkem** [comment]
folderName: "Protonet Messenger", //mandatory for android
fileName: 'resize.jpg' //mandatory for iOS

Thanks to "okhioktanio". 

People are having same issues with this plugin after 2 years. It cost me an hour to find out fix this issue on iOS and Android.

How is it hard to write a proper documentation and throw an exception if the given parameters not valid?

IONIC team is pushing this plugin on their website with misleading documentation. Even though they say filename is optional and there is default value, you still have to set the value.

**Comment by JoschkaSchulz** [comment]
I will add that to the readme (a bit late after 2 years, but at least I do it)
