### ISSUE TITLE
“Cannot read property 'apply' of undefined”

### ISSUE THREAD

**Issue by ejiyuan** [protonet/cordova-plugin-image-resizer#22]
“Cannot read property 'apply' of undefined”
my code
`getPicture() {
        var options: CameraOptions = {
            destinationType: Camera.DestinationType.FILE_URI, 
            sourceType: Camera.PictureSourceType.PHOTOLIBRARY, 
            allowEdit: true,
            mediaType: 0,

        };
       
        Camera.getPicture(options).then((fileUri) => {
            let options: ImageResizerOptions = {
                uri: fileUri,
                folderName: cordova.file.externalCacheDirectory,
                quality: 90,
                width: 1280,
                height: 1280
            };
            ImageResizer.resize(options).then(img => {
                var d = img;
            }).catch(err => {
                alert(err)
            });
        });`

**Comment by JoschkaSchulz** [comment]
do you solved the problem? What was the problem?

**Comment by ejiyuan** [comment]
I am sorry that my argument name "options" repeated！
