### ISSUE TITLE
ios bug

### ISSUE THREAD

**Issue by cataragak90** [protonet/cordova-plugin-image-resizer#24]
Hello!
it doesn't work for iOS, nothing happens when I use it:
ionic 2 code ex:
//Start
 Camera.getPicture(options).then((imageUrl) => {
       console.log(imageUrl); //it's displayed the right image path
       let options = {
          uri: results[i],
          quality: 70,
          width: 570,
          height: 430
        } as ImageResizerOptions;
        //Starting with this line nothing happens, any error/log displayed
        ImageResizer.resize(options)
            .then((filePath) => {
                  console.log(filePath);
                }, err => {
                 console.log(err);
                }
            );
      }
    });
PS: on android it works fine

Thanks, Victor

**Comment by FROST-D** [comment]
try this : #16

**Comment by JoschkaSchulz** [comment]
The fileName was missing. I have changed the readme for that.
