### ISSUE TITLE
need package.json for ionic-cli 3.1.2 and cordova 7

### ISSUE THREAD

**Issue by thewavelet** [protonet/cordova-plugin-image-resizer#25]
https://forum.ionicframework.com/t/i-can-not-add-plugin-imagepicker/90318

like this issue, need to add package.json file.

https://github.com/driftyco/ionic-cli/issues/2208
https://github.com/apache/cordova-docs/pull/699/files#r114967465

https://github.com/Telerik-Verified-Plugins/ImagePicker (for cordova 6 without package.json)
https://github.com/Keko94/ImagePicker (for cordova 7 with pacakge.json )

**Comment by alexislg2** [comment]
What is the workaround here?

**Comment by thewavelet** [comment]
https://github.com/candicom/cordova-plugin-image-resizer
