### ISSUE TITLE
Exif Lost

### ISSUE THREAD

**Issue by alexislg2** [protonet/cordova-plugin-image-resizer#26]
Hey,
I am afraid that thid plugin is losing all the EXIF data after resizing!

It means that the portrait pictures will be saved as landscape, which is a main issue.

I'm using Android Samsung A5

**Comment by JoschkaSchulz** [comment]
That could be really a problem,... I havn't spend much time on this plugin in the last time and maybe it could need some tests that something like that don't happens. If you like you could create a pull request or I will do it if I have time (but I can't say when I have enough time for that)

**Comment by alexislg2** [comment]
Thanks for your help. Why only keep orientation? GPS data is also very important. I would like to help but this is not in my skills

**Comment by JoschkaSchulz** [comment]
Oh I just linked the other issue because it seems for me all the same problem, it's not like that one thing that gets lost

**Comment by JoschkaSchulz** [comment]
should be fixed by https://github.com/JoschkaSchulz/cordova-plugin-image-resizer/pull/43
