### ISSUE TITLE
Is this plugin works in Ionic 1

### ISSUE THREAD

**Issue by alkahtani** [protonet/cordova-plugin-image-resizer#30]
I have real problem on resizing images before upload to firebase in my Ionic 1 app , i just found this plugin and i hope it can help me , can any one advise if it is tested in ionic 1 app .

**Comment by JoschkaSchulz** [comment]
Hey I wrote it a few years ago and havn't tested it in any other framework then cordova.

**Comment by alkahtani** [comment]
@JoschkaSchulz I have tested the plugin in ionic 1  and it is working perfectly , many thanks
