### ISSUE TITLE
Need image orientation

### ISSUE THREAD

**Issue by e-vural** [protonet/cordova-plugin-image-resizer#31]
If you add orientation option this plugin will be best

**Comment by JoschkaSchulz** [comment]
could be a problem of this issue: https://github.com/JoschkaSchulz/cordova-plugin-image-resizer/issues/26

**Comment by JoschkaSchulz** [comment]
should be fixed by https://github.com/JoschkaSchulz/cordova-plugin-image-resizer/pull/43
