### ISSUE TITLE
Android build fails without cordova-plugin-camera

### ISSUE THREAD

**Issue by EternallLight** [protonet/cordova-plugin-image-resizer#33]
Hello,

After installing the plugin on Android platform, I get the following error:

```
/platforms/android/src/info/protonet/imageresizer/ImageResizer.java:12: error: package org.apache.cordova.camera does not exist
import org.apache.cordova.camera.FileHelper;
```

Guess, this happens because of missing [FileHelper](https://github.com/apache/cordova-plugin-camera/blob/master/src/android/FileHelper.java) class from cordova-plugin-camera. I tried copying getInputStreamFromUriString to this plugin, but it requires other imports and methods, so I gave up after dozens of build errors.

I guess we should specify dependency on cordova-plugin-camera in your plugin.xml or ship the FileHelper with the plugin.

**Comment by congbao1991** [comment]
ionic cordova plugin add cordova-plugin-camera
npm install --save @ionic-native/camera

Completing these two steps can solve the problem

**Comment by JoschkaSchulz** [comment]
I setup everything and run in the same problem, I will add it to the readme
