### ISSUE TITLE
Unable to use the resize function

### ISSUE THREAD

**Issue by supportreq** [protonet/cordova-plugin-image-resizer#34]
I am unable to use the resize function in iOS... it is giving the following error:

TypeError: undefined is not an object (evaluating 'window.ImageResizer.resize')

please advice..

**Comment by JoschkaSchulz** [comment]
Do you have more then just this one line?

**Comment by supportreq** [comment]
@JoschkaSchulz no getting only this and error is raised by jquery.min.js

**Comment by xgenem** [comment]
@supportreq are you using a framework? Can you post a snippet of your code?

**Comment by JoschkaSchulz** [comment]
could be the missing fileName, I corrected the readme about what do you need on iOS and android.
