### ISSUE TITLE
PR for base64 for android and option to fit within bounds

### ISSUE THREAD

**Issue by kdcro101** [protonet/cordova-plugin-image-resizer#37]
@JoschkaSchulz,
Are you open for PR?

I've made following enhancements (all for android):
- accept base64 data-uri as input
- option `fit` to fit input image within bounds (options.width and options.height)
- output as base64 string

**Comment by Saturnyn** [comment]
@kdcro101 This sounds good!
Was the PR accepted ?

**Comment by kdcro101** [comment]
@Saturnyn ,

Haven't posted it yet. Wanted to see if repo is alive.
If @JoschkaSchulz is opened to it, I will post it.

**Comment by JoschkaSchulz** [comment]
I hadn't much time for that repo and the answer is really late,... but as less time I have I try to check and merge the pull requests I see as fast as possible. I will close this issue because it's nearly 2 month old, but if you like to add something via pull request I would like to merge that. :)
