### ISSUE TITLE
Plugin does not compile with latest version of Java 

### ISSUE THREAD

**Issue by mmc1ntyre** [protonet/cordova-plugin-image-resizer#4]
Plugin does not compile with latest version of java.

build 1.8.0_66-b17

[removed for brevity]/ImageResizer.java:15: error: cannot find symbol
import org.apache.cordova.FileHelper;
                         ^
  symbol:   class FileHelper
  location: package org.apache.cordova
[removed for brevity]/protonet/imageresizer/ImageResizer.java:84: error: cannot find symbol
      BitmapFactory.decodeStream(FileHelper.getInputStreamFromUriString(uriString, cordova), null, options);
                                 ^
  symbol:   variable FileHelper
  location: class ImageResizer
[removed for brevity]/protonet/imageresizer/ImageResizer.java:91: error: cannot find symbol
      Bitmap unscaledBitmap = BitmapFactory.decodeStream(FileHelper.getInputStreamFromUriString(uriString, cordova), null, options);
                                                         ^
  symbol:   variable FileHelper
  location: class ImageResizer

**Comment by mmc1ntyre** [comment]
Sorry.  My mistake.

**Comment by ManicMapple** [comment]
@mmc1ntyre what was your mistake? Please share
