### ISSUE TITLE
Please add the fileName(String) option for IOS too. Currently it only supports android and windows

### ISSUE THREAD

**Issue by ferrarikarthik** [protonet/cordova-plugin-image-resizer#40]
Currently as mentioned in the doc fileName(String): A custom name for the file. Default name is a timestamp. android and windows only. Could you please add this support to IOS. This will be of great help as it will work in all 3 platforms.

**Comment by JoschkaSchulz** [comment]
sounds like an good idea... I saw just tonight that at the moment every of the platforms work way to different,... they should move more closer together

**Comment by JoschkaSchulz** [comment]
Just saw in the code that fileName is already in iOS
