### ISSUE TITLE
Image proportion

### ISSUE THREAD

**Issue by jfoclpf** [protonet/cordova-plugin-image-resizer#41]
Thanks for the great free plugin.

Documentation should be slightly more clear. I don't clearly get if the proportion of the image is changed.

```
      width: 1280,
      height: 1280
```

Shouldn't it work also by just providing either `width` or `height` and not mandatorily both?

Thanks

**Comment by JoschkaSchulz** [comment]
Nice I could help you (and not me everyone who contributed to this project)

ehm I'm not sure anymore, it's a long time I wrote that and I'm wondering that it got used so much :) If I remember correctly it was meant for you get an image and don't know the size but wants a aaa x bbb sized image for displaying somewhere... so you can enter the width and the height and the plugin should take the best ratio of the image that fits... but not 100% sure anymore... sorry

**Comment by jfoclpf** [comment]
Thanks

I confirm it is like you said. The ratio is preserved.
