### ISSUE TITLE
Mismatch in ID/Package name causing double addition of plugin to package.json

### ISSUE THREAD

**Issue by keyz182** [protonet/cordova-plugin-image-resizer#44]
In package.json and config.xml, this plugin has an ID of "info.protonet.imageresizer" but has a name of "cordova-plugin-image-resizer" in package.json. This is confusing either npm, Ionic, or cordova, and causing the plugin to be put into package.json twice:

```
"cordova-plugin-image-resizer": "https://github.com/protonet/cordova-plugin-image-resizer.git", 
"info.protonet.imageresizer": "https://github.com/protonet/cordova-plugin-image-resizer.git"
```

The simple solution seems to be to make these match. I would submit a PR, but I'm not sure what name would be preferable.

**Comment by JoschkaSchulz** [comment]
Does something break if we rename the info.protonet.imageresizer to cordova-plugin-image-resizer? If that wouldn't break anything I would recommand that way... sadly I can't test it currently so if you like to rename it, test it shortly if it works then I would merge it :)

**Comment by JoschkaSchulz** [comment]
is merged
